# é’‰é’‰æœºå™¨äººé…ç½®
dingtalk:
  webhook: "https://oapi.dingtalk.com/robot/send?access_token=2d0adfdb37a9cd21673c6c8919a06cb2f4586bdcfcd1cb1b9e635ec24b9b53e4"
  secret: "SEC85e9e8c1a8392c305d12e34e844dc9739a628ace5532659680043ffc5f8cf714"

# LeetCodeç”¨æˆ·é…ç½®
leetcode:
  minimum_solved: 3  # æœ€å°è§£é¢˜æ•°é‡è¦æ±‚
  users:
    - url: "https://leetcode.cn/u/kan-fan-xing/"
      name: "å®èµµæ˜Ÿ"
    - url: "https://leetcode.cn/u/xun_xun/"
      name: "è’‹ç¿å‹‹"
    - url: "https://leetcode.cn/u/zao-an-e/"
      name: "é›ªæ€¡ç¦"
    - url: "https://leetcode.cn/u/gui-tu-960/"
      name: "æ–¹è…¾é£"
    - url: "https://leetcode.cn/u/ding-mao-s/"
      name: "ç”°å®¶æ°"
    - url: "https://leetcode.cn/u/trusting-6rothendieckqgx/"
      name: "è´ºä¸½å¸†"
    - url: "https://leetcode.cn/u/6oofy-gangulyxsi/"
      name: "éŸ©ç¡•åš"
    - url: "https://leetcode.cn/u/practical-snyderqvy/"
      name: "ç‹æ€¡æ™—"
    - url: "https://leetcode.cn/u/hardcore-swirlesrz0/"
      name: "ç‹ç‰é¾™"
    - url: "https://leetcode.cn/u/festive-i2ubinwnk/"
      name: "æå£®"
  semester_start: "2025-02-17"

ding_message:
  header: "å„ä½ç®—æ³•å°èƒ½æ‰‹æ³¨æ„æŸ¥æ”¶æœ¬å‘¨æˆ˜æŠ¥~ \n ------âœ¨æœ¬å‘¨æˆ˜ç»©é€Ÿè§ˆâœ¨------"
  bottom: "ğŸ’¡æ¸©é¦¨æé†’ï¼š\n ä¿æŒè§£é¢˜èŠ‚å¥å°±åƒæ‰“æ¸¸æˆç­¾åˆ°é¢†é‡‘å¸ï¼Œè¿ç»­ç™»å½•ä¼šæœ‰æƒŠå–œåŠ æˆå“¦~ æš‚æ—¶è½åçš„åŒå­¦åˆ«ç€æ€¥ï¼Œä¸‹å‘¨ã€Œè¡¥é¢˜buffã€å·²ç”Ÿæ•ˆï¼\n ä»£ç ä¸æ¯ï¼Œåˆ·é¢˜ä¸æ­¢ \n æˆ‘ä»¬ä¸‹å‘¨åŒä¸€æ—¶é—´ï¼Œç»§ç»­è§è¯æˆé•¿ï¼( â€¢Ì€ Ï‰ â€¢Ì )âœ§ \n  ï¼ˆæœ‰ä»»ä½•å»ºè®®æ¬¢è¿éšæ—¶æ»´æ»´~ï¼‰"